### ISSUE TITLE
RuntimeError: invalid argument 0: Tensors must have same number of dimensions

### ISSUE THREAD

**Issue by astier** [mjacar/pytorch-nec#5]
A RuntimeError gets thrown:

> Traceback (most recent call last):
  File "run_nec.py", line 35, in <module>
    main(args.env, args.embedding_size)
  File "run_nec.py", line 23, in main
    reward = agent.episode()
  File "nec_agent.py", line 179, in episode
    self.update()
  File "nec_agent.py", line 135, in update
    dnd.insert(state_embedding.detach(), Q_N.detach().unsqueeze(0))
  File "dnd.py", line 68, in insert
    [self.values_to_be_inserted, value.data], 0)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 1 and 2 at /opt/conda/conda-bld/pytorch-cpu_1524577316810/work/aten/src/TH/generic/THTensorMath.c:3577

**Comment by mjacar** [comment]
This repo was made against a specific version of PyTorch. Unsurprisingly, there have since been a number of breaking changes. I made https://github.com/mjacar/pytorch-nec/pull/6 to make the setup instructions more clear. I don't presently have any plans to update this repo to the most recent version of PyTorch, so if you want to do so, I would advise you to fork this repo.
